# permissions for end users to view pvpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvpool-viewer-role
rules:
  - apiGroups:
      - pvpool.noobaa.com
    resources:
      - pvpools
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - pvpool.noobaa.com
    resources:
      - pvpools/status
    verbs:
      - get
